version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7

    working_directory: ~/devops

    steps:
      # Step 1
      - checkout
      # Step 2
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      # Step 3
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            flake8 --exclude=venv* --statistics
            # pytest -v --cov=calculator
            pytest --junitxml=test-results/junit.xml

      - store_test_results:
          path: test-results

      # Step 4: Deploy
      - run:
          name: deploy
          command: |
            dir=DEPLOY-$(date +"%Y%m%d-%H:%M:%S")
            mkdir $dir
            cp ./calculator/calculator.py ./$dir

      - store_artifacts:
          path: $dir
            